
CONST_INT NUM_VEHICLES_COMPACT       23
CONST_INT NUM_VEHICLES_SEDAN         42
CONST_INT NUM_VEHICLES_SUV           46
CONST_INT NUM_VEHICLES_COUPE         20
CONST_INT NUM_VEHICLES_MUSCLE        91
CONST_INT NUM_VEHICLES_SPORT_CLASSIC 50
CONST_INT NUM_VEHICLES_SPORT         119
CONST_INT NUM_VEHICLES_SUPER         57
CONST_INT NUM_VEHICLES_MOTORCYCLE    58
CONST_INT NUM_VEHICLES_OFF_ROAD      68
CONST_INT NUM_VEHICLES_INDUSTRIAL    11
CONST_INT NUM_VEHICLES_UTILITY       50
CONST_INT NUM_VEHICLES_VAN           41
CONST_INT NUM_VEHICLES_CYCLE         9
CONST_INT NUM_VEHICLES_BOAT          26
CONST_INT NUM_VEHICLES_HELICOPTER    30
CONST_INT NUM_VEHICLES_PLANE         46
CONST_INT NUM_VEHICLES_SERVICE       13
CONST_INT NUM_VEHICLES_EMERGENCY     31
CONST_INT NUM_VEHICLES_MILITARY      17
CONST_INT NUM_VEHICLES_COMMERCIAL    23
CONST_INT NUM_VEHICLES_RAIL          11
CONST_INT NUM_VEHICLES_OPEN_WHEEL    4

FUNC VEHICLE_INDEX UTIL_VEHICLE_GET_CURRENT()
    RETURN GET_VEHICLE_PED_IS_IN(PLAYER_PED_ID(), TRUE)
ENDFUNC

// TO-DO: Fix this.
FUNC VEHICLE_INDEX UTIL_VEHICLE_GET_CURRENT_PV()
    BLIP_INDEX biBlip = GET_FIRST_BLIP_INFO_ID(RADAR_GANG_VEHICLE)
    IF DOES_BLIP_EXIST(biBlip)
        RETURN GET_VEHICLE_INDEX_FROM_ENTITY_INDEX(GET_BLIP_INFO_ID_ENTITY_INDEX(biBlip))
    ENDIF
	
    RETURN NULL
ENDFUNC

FUNC VECTOR UTIL_VEHICLE_GET_SPAWN_LOCATION(INT iVehicleModel)
    FLOAT fYOffset = 0.0

    IF UTIL_VEHICLE_GET_CURRENT() <> NULL
        VECTOR vMin, vMax, vResult
        GET_MODEL_DIMENSIONS(iVehicleModel, vMin, vMax)
        vResult = vMax - vMin
        fYOffset = vResult.y
    ENDIF

    RETURN GET_OFFSET_FROM_ENTITY_IN_WORLD_COORDS(PLAYER_PED_ID(), <<0.0, fYOffset, 0.0>>)
ENDFUNC

FUNC INT UTIL_VEHICLE_GET_NUM_VEHICLES_IN_CLASS(VEHICLE_CLASS eClass)
    SWITCH eClass
        CASE VC_COMPACT       RETURN NUM_VEHICLES_COMPACT
        CASE VC_SEDAN         RETURN NUM_VEHICLES_SEDAN
        CASE VC_SUV           RETURN NUM_VEHICLES_SUV
        CASE VC_COUPE         RETURN NUM_VEHICLES_COUPE
        CASE VC_MUSCLE        RETURN NUM_VEHICLES_MUSCLE
        CASE VC_SPORT_CLASSIC RETURN NUM_VEHICLES_SPORT_CLASSIC
        CASE VC_SPORT         RETURN NUM_VEHICLES_SPORT
        CASE VC_SUPER         RETURN NUM_VEHICLES_SUPER
        CASE VC_MOTORCYCLE    RETURN NUM_VEHICLES_MOTORCYCLE
        CASE VC_OFF_ROAD      RETURN NUM_VEHICLES_OFF_ROAD
        CASE VC_INDUSTRIAL    RETURN NUM_VEHICLES_INDUSTRIAL
        CASE VC_UTILITY       RETURN NUM_VEHICLES_UTILITY
        CASE VC_VAN           RETURN NUM_VEHICLES_VAN
        CASE VC_CYCLE         RETURN NUM_VEHICLES_CYCLE
        CASE VC_BOAT          RETURN NUM_VEHICLES_BOAT
        CASE VC_HELICOPTER    RETURN NUM_VEHICLES_HELICOPTER
        CASE VC_PLANE         RETURN NUM_VEHICLES_PLANE
        CASE VC_SERVICE       RETURN NUM_VEHICLES_SERVICE
        CASE VC_EMERGENCY     RETURN NUM_VEHICLES_EMERGENCY
        CASE VC_MILITARY      RETURN NUM_VEHICLES_MILITARY
        CASE VC_COMMERCIAL    RETURN NUM_VEHICLES_COMMERCIAL
        CASE VC_RAIL          RETURN NUM_VEHICLES_RAIL
        CASE VC_OPEN_WHEEL    RETURN NUM_VEHICLES_OPEN_WHEEL
    ENDSWITCH
	
    RETURN 0
ENDFUNC

FUNC INT UTIL_VEHICLE_GET_VEHICLE_HASH_FROM_CLASS_BY_INDEX(VEHICLE_CLASS eClass, INT iVehicleIndex)
    SWITCH eClass
        CASE VC_COMPACT
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("ARBITERGT")
                CASE 1  RETURN HASH("ASBO")
                CASE 2  RETURN HASH("ASTRON2")
                CASE 3  RETURN HASH("BLISTA")
                CASE 4  RETURN HASH("BRIOSO")
                CASE 5  RETURN HASH("BRIOSO2")
                CASE 6  RETURN HASH("BRIOSO3")
                CASE 7  RETURN HASH("CLUB")
                CASE 8  RETURN HASH("CYCLONE2")
                CASE 9  RETURN HASH("DILETTANTE")
                CASE 10 RETURN HASH("DILETTANTE2")
                CASE 11 RETURN HASH("IGNUS2")
                CASE 12 RETURN HASH("ISSI2")
                CASE 13 RETURN HASH("ISSI3")
                CASE 14 RETURN HASH("ISSI4")
                CASE 15 RETURN HASH("ISSI5")
                CASE 16 RETURN HASH("ISSI6")
                CASE 17 RETURN HASH("KANJO")
                CASE 18 RETURN HASH("PANTO")
                CASE 19 RETURN HASH("PRAIRIE")
                CASE 20 RETURN HASH("RHAPSODY")
                CASE 21 RETURN HASH("S95")
                CASE 22 RETURN HASH("WEEVIL")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_SEDAN
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("ASEA")
                CASE 1  RETURN HASH("ASEA2")
                CASE 2  RETURN HASH("ASTEROPE")
                CASE 3  RETURN HASH("ASTEROPE2")
                CASE 4  RETURN HASH("CHAVOSV6")
                CASE 5  RETURN HASH("CINQUEMILA")
                CASE 6  RETURN HASH("COG55")
                CASE 7  RETURN HASH("COG552")
                CASE 8  RETURN HASH("COGNOSCENTI")
                CASE 9  RETURN HASH("COGNOSCENTI2")
                CASE 10 RETURN HASH("DEITY")
                CASE 11 RETURN HASH("DRIFTVORSCHLAG")
                CASE 12 RETURN HASH("EMPEROR")
                CASE 13 RETURN HASH("EMPEROR2")
                CASE 14 RETURN HASH("EMPEROR3")
                CASE 15 RETURN HASH("FUGITIVE")
                CASE 16 RETURN HASH("GLENDALE")
                CASE 17 RETURN HASH("GLENDALE2")
                CASE 18 RETURN HASH("INGOT")
                CASE 19 RETURN HASH("INTRUDER")
                CASE 20 RETURN HASH("LIMO2")
                CASE 21 RETURN HASH("PREMIER")
                CASE 22 RETURN HASH("PRIMO")
                CASE 23 RETURN HASH("PRIMO2")
                CASE 24 RETURN HASH("REGINA")
                CASE 25 RETURN HASH("RHINEHART")
                CASE 26 RETURN HASH("ROMERO")
                CASE 27 RETURN HASH("SCHAFTER2")
                CASE 28 RETURN HASH("SCHAFTER5")
                CASE 29 RETURN HASH("SCHAFTER6")
                CASE 30 RETURN HASH("STAFFORD")
                CASE 31 RETURN HASH("STANIER")
                CASE 32 RETURN HASH("STRATUM")
                CASE 33 RETURN HASH("STRETCH")
                CASE 34 RETURN HASH("SUPERD")
                CASE 35 RETURN HASH("SURGE")
                CASE 36 RETURN HASH("TAILGATER")
                CASE 37 RETURN HASH("TAILGATER2")
                CASE 38 RETURN HASH("VORSCHLAGHAMMER")
                CASE 39 RETURN HASH("WARRENER")
                CASE 40 RETURN HASH("WARRENER2")
                CASE 41 RETURN HASH("WASHINGTON")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_SUV
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("ALEUTIAN")
                CASE 1  RETURN HASH("ASTRON")
                CASE 2  RETURN HASH("BALLER")
                CASE 3  RETURN HASH("BALLER2")
                CASE 4  RETURN HASH("BALLER3")
                CASE 5  RETURN HASH("BALLER4")
                CASE 6  RETURN HASH("BALLER5")
                CASE 7  RETURN HASH("BALLER6")
                CASE 8  RETURN HASH("BALLER7")
                CASE 9  RETURN HASH("BALLER8")
                CASE 10 RETURN HASH("BJXL")
                CASE 11 RETURN HASH("CASTIGATOR")
                CASE 12 RETURN HASH("CAVALCADE")
                CASE 13 RETURN HASH("CAVALCADE2")
                CASE 14 RETURN HASH("CAVALCADE3")
                CASE 15 RETURN HASH("CONTENDER")
                CASE 16 RETURN HASH("DORADO")
                CASE 17 RETURN HASH("DUBSTA")
                CASE 18 RETURN HASH("DUBSTA2")
                CASE 19 RETURN HASH("FQ2")
                CASE 20 RETURN HASH("GRANGER")
                CASE 21 RETURN HASH("GRANGER2")
                CASE 22 RETURN HASH("GRESLEY")
                CASE 23 RETURN HASH("HABANERO")
                CASE 24 RETURN HASH("HUNTLEY")
                CASE 25 RETURN HASH("ISSI8")
                CASE 26 RETURN HASH("IWAGEN")
                CASE 27 RETURN HASH("JUBILEE")
                CASE 28 RETURN HASH("LANDSTALKER")
                CASE 29 RETURN HASH("LANDSTALKER2")
                CASE 30 RETURN HASH("MESA")
                CASE 31 RETURN HASH("MESA2")
                CASE 32 RETURN HASH("NOVAK")
                CASE 33 RETURN HASH("PATRIOT")
                CASE 34 RETURN HASH("PATRIOT2")
                CASE 35 RETURN HASH("RADI")
                CASE 36 RETURN HASH("REBLA")
                CASE 37 RETURN HASH("ROCOTO")
                CASE 38 RETURN HASH("SEMINOLE")
                CASE 39 RETURN HASH("SEMINOLE2")
                CASE 40 RETURN HASH("SERRANO")
                CASE 41 RETURN HASH("SQUADDIE")
                CASE 42 RETURN HASH("TOROS")
                CASE 43 RETURN HASH("VIVANITE")
                CASE 44 RETURN HASH("XLS")
                CASE 45 RETURN HASH("XLS2")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_COUPE
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("COGCABRIO")
                CASE 1  RETURN HASH("DRIFTFR36")
                CASE 2  RETURN HASH("EUROSX32")
                CASE 3  RETURN HASH("EXEMPLAR")
                CASE 4  RETURN HASH("F620")
                CASE 5  RETURN HASH("FELON")
                CASE 6  RETURN HASH("FELON2")
                CASE 7  RETURN HASH("FR36")
                CASE 8  RETURN HASH("JACKAL")
                CASE 9  RETURN HASH("KANJOSJ")
                CASE 10 RETURN HASH("ORACLE")
                CASE 11 RETURN HASH("ORACLE2")
                CASE 12 RETURN HASH("POSTLUDE")
                CASE 13 RETURN HASH("PREVION")
                CASE 14 RETURN HASH("SENTINEL")
                CASE 15 RETURN HASH("SENTINEL2")
                CASE 16 RETURN HASH("WINDSOR")
                CASE 17 RETURN HASH("WINDSOR2")
                CASE 18 RETURN HASH("ZION")
                CASE 19 RETURN HASH("ZION2")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_MUSCLE
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("BLADE")
                CASE 1  RETURN HASH("BRIGHAM")
                CASE 2  RETURN HASH("BROADWAY")
                CASE 3  RETURN HASH("BUCCANEER")
                CASE 4  RETURN HASH("BUCCANEER2")
                CASE 5  RETURN HASH("BUFFALO4")
                CASE 6  RETURN HASH("BUFFALO5")
                CASE 7  RETURN HASH("CHINO")
                CASE 8  RETURN HASH("CHINO2")
                CASE 9  RETURN HASH("CLIQUE")
                CASE 10 RETURN HASH("CLIQUE2")
                CASE 11 RETURN HASH("COQUETTE3")
                CASE 12 RETURN HASH("DEVIANT")
                CASE 13 RETURN HASH("DOMINATOR")
                CASE 14 RETURN HASH("DOMINATOR2")
                CASE 15 RETURN HASH("DOMINATOR3")
                CASE 16 RETURN HASH("DOMINATOR4")
                CASE 17 RETURN HASH("DOMINATOR5")
                CASE 18 RETURN HASH("DOMINATOR6")
                CASE 19 RETURN HASH("DOMINATOR7")
                CASE 20 RETURN HASH("DOMINATOR8")
                CASE 21 RETURN HASH("DOMINATOR9")
                CASE 22 RETURN HASH("DOMINATOR10")
                CASE 23 RETURN HASH("DRIFTYOSEMITE")
                CASE 24 RETURN HASH("DUKES")
                CASE 25 RETURN HASH("DUKES2")
                CASE 26 RETURN HASH("DUKES3")
                CASE 27 RETURN HASH("ELLIE")
                CASE 28 RETURN HASH("EUDORA")
                CASE 29 RETURN HASH("FACTION")
                CASE 30 RETURN HASH("FACTION2")
                CASE 31 RETURN HASH("FACTION3")
                CASE 32 RETURN HASH("GAUNTLET")
                CASE 33 RETURN HASH("GAUNTLET2")
                CASE 34 RETURN HASH("GAUNTLET3")
                CASE 35 RETURN HASH("GAUNTLET4")
                CASE 36 RETURN HASH("GAUNTLET5")
                CASE 37 RETURN HASH("GREENWOOD")
                CASE 38 RETURN HASH("HERMES")
                CASE 39 RETURN HASH("HOTKNIFE")
                CASE 40 RETURN HASH("HUSTLER")
                CASE 41 RETURN HASH("IMPALER")
                CASE 42 RETURN HASH("IMPALER2")
                CASE 43 RETURN HASH("IMPALER3")
                CASE 44 RETURN HASH("IMPALER4")
                CASE 45 RETURN HASH("IMPALER5")
                CASE 46 RETURN HASH("IMPALER6")
                CASE 47 RETURN HASH("IMPERATOR")
                CASE 48 RETURN HASH("IMPERATOR2")
                CASE 49 RETURN HASH("IMPERATOR3")
                CASE 50 RETURN HASH("LURCHER")
                CASE 51 RETURN HASH("MANANA2")
                CASE 52 RETURN HASH("MOONBEAM")
                CASE 53 RETURN HASH("MOONBEAM2")
                CASE 54 RETURN HASH("NIGHTSHADE")
                CASE 55 RETURN HASH("PEYOTE2")
                CASE 56 RETURN HASH("PHOENIX")
                CASE 57 RETURN HASH("PICADOR")
                CASE 58 RETURN HASH("RATLOADER")
                CASE 59 RETURN HASH("RATLOADER2")
                CASE 60 RETURN HASH("RUINER")
                CASE 61 RETURN HASH("RUINER2")
                CASE 62 RETURN HASH("RUINER3")
                CASE 63 RETURN HASH("RUINER4")
                CASE 64 RETURN HASH("SABREGT")
                CASE 65 RETURN HASH("SABREGT2")
                CASE 66 RETURN HASH("SLAMVAN")
                CASE 67 RETURN HASH("SLAMVAN2")
                CASE 68 RETURN HASH("SLAMVAN3")
                CASE 69 RETURN HASH("SLAMVAN4")
                CASE 70 RETURN HASH("SLAMVAN5")
                CASE 71 RETURN HASH("SLAMVAN6")
                CASE 72 RETURN HASH("STALION")
                CASE 73 RETURN HASH("STALION2")
                CASE 74 RETURN HASH("TAHOMA")
                CASE 75 RETURN HASH("TAMPA")
                CASE 76 RETURN HASH("TAMPA3")
                CASE 77 RETURN HASH("TULIP")
                CASE 78 RETURN HASH("TULIP2")
                CASE 79 RETURN HASH("VAMOS")
                CASE 80 RETURN HASH("VIGERO")
                CASE 81 RETURN HASH("VIGERO2")
                CASE 82 RETURN HASH("VIGERO3")
                CASE 83 RETURN HASH("VIRGO")
                CASE 84 RETURN HASH("VIRGO2")
                CASE 85 RETURN HASH("VIRGO3")
                CASE 86 RETURN HASH("VOODOO")
                CASE 87 RETURN HASH("VOODOO2")
                CASE 88 RETURN HASH("WEEVIL2")
                CASE 89 RETURN HASH("YOSEMITE")
                CASE 90 RETURN HASH("YOSEMITE2")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_SPORT_CLASSIC
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("ARDENT")
                CASE 1  RETURN HASH("BTYPE")
                CASE 2  RETURN HASH("BTYPE2")
                CASE 3  RETURN HASH("BTYPE3")
                CASE 4  RETURN HASH("CASCO")
                CASE 5  RETURN HASH("CHEBUREK")
                CASE 6  RETURN HASH("CHEETAH2")
                CASE 7  RETURN HASH("COQUETTE2")
                CASE 8  RETURN HASH("COQUETTE5")
                CASE 9  RETURN HASH("DELUXO")
                CASE 10 RETURN HASH("DRIFTCHEBUREK")
                CASE 11 RETURN HASH("DRIFTJESTER3")
                CASE 12 RETURN HASH("DRIFTNEBULA")
                CASE 13 RETURN HASH("DYNASTY")
                CASE 14 RETURN HASH("FAGALOA")
                CASE 15 RETURN HASH("FELTZER3")
                CASE 16 RETURN HASH("GT500")
                CASE 17 RETURN HASH("INFERNUS2")
                CASE 18 RETURN HASH("JB700")
                CASE 19 RETURN HASH("JB7002")
                CASE 20 RETURN HASH("MAMBA")
                CASE 21 RETURN HASH("MANANA")
                CASE 22 RETURN HASH("MICHELLI")
                CASE 23 RETURN HASH("MONROE")
                CASE 24 RETURN HASH("NEBULA")
                CASE 25 RETURN HASH("PEYOTE")
                CASE 26 RETURN HASH("PEYOTE3")
                CASE 27 RETURN HASH("PIGALLE")
                CASE 28 RETURN HASH("RAPIDGT3")
                CASE 29 RETURN HASH("RETINUE")
                CASE 30 RETURN HASH("RETINUE2")
                CASE 31 RETURN HASH("SAVESTRA")
                CASE 32 RETURN HASH("STINGER")
                CASE 33 RETURN HASH("STINGERGT")
                CASE 34 RETURN HASH("STROMBERG")
                CASE 35 RETURN HASH("SWINGER")
                CASE 36 RETURN HASH("TOREADOR")
                CASE 37 RETURN HASH("TORERO")
                CASE 38 RETURN HASH("TORNADO")
                CASE 39 RETURN HASH("TORNADO2")
                CASE 40 RETURN HASH("TORNADO3")
                CASE 41 RETURN HASH("TORNADO4")
                CASE 42 RETURN HASH("TORNADO5")
                CASE 43 RETURN HASH("TORNADO6")
                CASE 44 RETURN HASH("TURISMO2")
                CASE 45 RETURN HASH("URANUS")
                CASE 46 RETURN HASH("VISERIS")
                CASE 47 RETURN HASH("Z190")
                CASE 48 RETURN HASH("ZION3")
                CASE 49 RETURN HASH("ZTYPE")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_SPORT
            SWITCH iVehicleIndex
                CASE 0   RETURN HASH("ALPHA")
                CASE 1   RETURN HASH("BANSHEE")
                CASE 2   RETURN HASH("BANSHEE3")
                CASE 3   RETURN HASH("BESTIAGTS")
                CASE 4   RETURN HASH("BLISTA2")
                CASE 5   RETURN HASH("BLISTA3")
                CASE 6   RETURN HASH("BUFFALO")
                CASE 7   RETURN HASH("BUFFALO2")
                CASE 8   RETURN HASH("BUFFALO3")
                CASE 9   RETURN HASH("CALICO")
                CASE 10  RETURN HASH("CARBONIZZARE")
                CASE 11  RETURN HASH("COMET2")
                CASE 12  RETURN HASH("COMET3")
                CASE 13  RETURN HASH("COMET4")
                CASE 14  RETURN HASH("COMET5")
                CASE 15  RETURN HASH("COMET6")
                CASE 16  RETURN HASH("COMET7")
                CASE 17  RETURN HASH("COQUETTE")
                CASE 18  RETURN HASH("COQUETTE4")
                CASE 19  RETURN HASH("COQUETTE6")
                CASE 20  RETURN HASH("CORSITA")
                CASE 21  RETURN HASH("COUREUR")
                CASE 22  RETURN HASH("CYPHER")
                CASE 23  RETURN HASH("DRAFTER")
                CASE 24  RETURN HASH("DRIFTCYPHER")
                CASE 25  RETURN HASH("DRIFTEUROS")
                CASE 26  RETURN HASH("DRIFTFUTO")
                CASE 27  RETURN HASH("DRIFTFUTO2")
                CASE 28  RETURN HASH("DRIFTJESTER")
                CASE 29  RETURN HASH("DRIFTREMUS")
                CASE 30  RETURN HASH("DRIFTSENTINEL")
                CASE 31  RETURN HASH("DRIFTTAMPA")
                CASE 32  RETURN HASH("DRIFTZR350")
                CASE 33  RETURN HASH("ELEGY")
                CASE 34  RETURN HASH("ELEGY2")
                CASE 35  RETURN HASH("ENVISAGE")
                CASE 36  RETURN HASH("EUROS")
                CASE 37  RETURN HASH("EVERON2")
                CASE 38  RETURN HASH("FELTZER2")
                CASE 39  RETURN HASH("FLASHGT")
                CASE 40  RETURN HASH("FUROREGT")
                CASE 41  RETURN HASH("FUSILADE")
                CASE 42  RETURN HASH("FUTO")
                CASE 43  RETURN HASH("FUTO2")
                CASE 44  RETURN HASH("GAUNTLET6")
                CASE 45  RETURN HASH("GB200")
                CASE 46  RETURN HASH("GROWLER")
                CASE 47  RETURN HASH("HOTRING")
                CASE 48  RETURN HASH("IMORGON")
                CASE 49  RETURN HASH("ISSI7")
                CASE 50  RETURN HASH("ITALIGTO")
                CASE 51  RETURN HASH("ITALIRSX")
                CASE 52  RETURN HASH("JESTER")
                CASE 53  RETURN HASH("JESTER2")
                CASE 54  RETURN HASH("JESTER3")
                CASE 55  RETURN HASH("JESTER4")
                CASE 56  RETURN HASH("JESTER5")
                CASE 57  RETURN HASH("JUGULAR")
                CASE 58  RETURN HASH("KHAMELION")
                CASE 59  RETURN HASH("KOMODA")
                CASE 60  RETURN HASH("KURUMA")
                CASE 61  RETURN HASH("KURUMA2")
                CASE 62  RETURN HASH("LOCUST")
                CASE 63  RETURN HASH("LYNX")
                CASE 64  RETURN HASH("MASSACRO")
                CASE 65  RETURN HASH("MASSACRO2")
                CASE 66  RETURN HASH("NEO")
                CASE 67  RETURN HASH("NEON")
                CASE 68  RETURN HASH("NINEF")
                CASE 69  RETURN HASH("NINEF2")
                CASE 70  RETURN HASH("NIOBE")
                CASE 71  RETURN HASH("OMNIS")
                CASE 72  RETURN HASH("OMNISEGT")
                CASE 73  RETURN HASH("PANTHERE")
                CASE 74  RETURN HASH("PARAGON")
                CASE 75  RETURN HASH("PARAGON2")
                CASE 76  RETURN HASH("PARAGON3")
                CASE 77  RETURN HASH("PARIAH")
                CASE 78  RETURN HASH("PENUMBRA")
                CASE 79  RETURN HASH("PENUMBRA2")
                CASE 80  RETURN HASH("R300")
                CASE 81  RETURN HASH("RAIDEN")
                CASE 82  RETURN HASH("RAPIDGT")
                CASE 83  RETURN HASH("RAPIDGT2")
                CASE 84  RETURN HASH("RAPTOR")
                CASE 85  RETURN HASH("REMUS")
                CASE 86  RETURN HASH("REVOLTER")
                CASE 87  RETURN HASH("RT3000")
                CASE 88  RETURN HASH("RUSTON")
                CASE 89  RETURN HASH("SCHAFTER3")
                CASE 90  RETURN HASH("SCHAFTER4")
                CASE 91  RETURN HASH("SCHLAGEN")
                CASE 92  RETURN HASH("SCHWARZER")
                CASE 93  RETURN HASH("SENTINEL3")
                CASE 94  RETURN HASH("SENTINEL4")
                CASE 95  RETURN HASH("SEVEN70")
                CASE 96  RETURN HASH("SM722")
                CASE 97  RETURN HASH("SPECTER")
                CASE 98  RETURN HASH("SPECTER2")
                CASE 99  RETURN HASH("STINGERTT")
                CASE 100 RETURN HASH("STREITER")
                CASE 101 RETURN HASH("SUGOI")
                CASE 102 RETURN HASH("SULTAN")
                CASE 103 RETURN HASH("SULTAN2")
                CASE 104 RETURN HASH("SULTAN3")
                CASE 105 RETURN HASH("SURANO")
                CASE 106 RETURN HASH("TAMPA2")
                CASE 107 RETURN HASH("TENF")
                CASE 108 RETURN HASH("TENF2")
                CASE 109 RETURN HASH("TROPOS")
                CASE 110 RETURN HASH("VECTRE")
                CASE 111 RETURN HASH("VERLIERER2")
                CASE 112 RETURN HASH("VETO")
                CASE 113 RETURN HASH("VETO2")
                CASE 114 RETURN HASH("VSTR")
                CASE 115 RETURN HASH("ZR350")
                CASE 116 RETURN HASH("ZR380")
                CASE 117 RETURN HASH("ZR3802")
                CASE 118 RETURN HASH("ZR3803")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_SUPER
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("ADDER")
                CASE 1  RETURN HASH("AUTARCH")
                CASE 2  RETURN HASH("BANSHEE2")
                CASE 3  RETURN HASH("BULLET")
                CASE 4  RETURN HASH("CHAMPION")
                CASE 5  RETURN HASH("CHEETAH")
                CASE 6  RETURN HASH("CYCLONE")
                CASE 7  RETURN HASH("DEVESTE")
                CASE 8  RETURN HASH("EMERUS")
                CASE 9  RETURN HASH("ENTITY2")
                CASE 10 RETURN HASH("ENTITY3")
                CASE 11 RETURN HASH("ENTITYXF")
                CASE 12 RETURN HASH("FMJ")
                CASE 13 RETURN HASH("FURIA")
                CASE 14 RETURN HASH("GP1")
                CASE 15 RETURN HASH("IGNUS")
                CASE 16 RETURN HASH("INFERNUS")
                CASE 17 RETURN HASH("ITALIGTB")
                CASE 18 RETURN HASH("ITALIGTB2")
                CASE 19 RETURN HASH("KRIEGER")
                CASE 20 RETURN HASH("LE7B")
                CASE 21 RETURN HASH("LM87")
                CASE 22 RETURN HASH("NERO")
                CASE 23 RETURN HASH("NERO2")
                CASE 24 RETURN HASH("OSIRIS")
                CASE 25 RETURN HASH("PENETRATOR")
                CASE 26 RETURN HASH("PFISTER811")
                CASE 27 RETURN HASH("PIPISTRELLO")
                CASE 28 RETURN HASH("PROTOTIPO")
                CASE 29 RETURN HASH("REAPER")
                CASE 30 RETURN HASH("S80")
                CASE 31 RETURN HASH("SC1")
                CASE 32 RETURN HASH("SCRAMJET")
                CASE 33 RETURN HASH("SHEAVA")
                CASE 34 RETURN HASH("SULTANRS")
                CASE 35 RETURN HASH("T20")
                CASE 36 RETURN HASH("TAIPAN")
                CASE 37 RETURN HASH("TEMPESTA")
                CASE 38 RETURN HASH("TEZERACT")
                CASE 39 RETURN HASH("THRAX")
                CASE 40 RETURN HASH("TIGON")
                CASE 41 RETURN HASH("TORERO2")
                CASE 42 RETURN HASH("TURISMO3")
                CASE 43 RETURN HASH("TURISMOR")
                CASE 44 RETURN HASH("TYRANT")
                CASE 45 RETURN HASH("TYRUS")
                CASE 46 RETURN HASH("VACCA")
                CASE 47 RETURN HASH("VAGNER")
                CASE 48 RETURN HASH("VIGILANTE")
                CASE 49 RETURN HASH("VIRTUE")
                CASE 50 RETURN HASH("VISIONE")
                CASE 51 RETURN HASH("VOLTIC")
                CASE 52 RETURN HASH("VOLTIC2")
                CASE 53 RETURN HASH("XA21")
                CASE 54 RETURN HASH("ZENO")
                CASE 55 RETURN HASH("ZENTORNO")
                CASE 56 RETURN HASH("ZORRUSSO")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_MOTORCYCLE
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("AKUMA")
                CASE 1  RETURN HASH("AVARUS")
                CASE 2  RETURN HASH("BAGGER")
                CASE 3  RETURN HASH("BATI")
                CASE 4  RETURN HASH("BATI2")
                CASE 5  RETURN HASH("BF400")
                CASE 6  RETURN HASH("CARBONRS")
                CASE 7  RETURN HASH("CHIMERA")
                CASE 8  RETURN HASH("CLIFFHANGER")
                CASE 9  RETURN HASH("DAEMON")
                CASE 10 RETURN HASH("DAEMON2")
                CASE 11 RETURN HASH("DEATHBIKE")
                CASE 12 RETURN HASH("DEATHBIKE2")
                CASE 13 RETURN HASH("DEATHBIKE3")
                CASE 14 RETURN HASH("DEFILER")
                CASE 15 RETURN HASH("DIABLOUS")
                CASE 16 RETURN HASH("DIABLOUS2")
                CASE 17 RETURN HASH("DOUBLE")
                CASE 18 RETURN HASH("ENDURO")
                CASE 19 RETURN HASH("ESSKEY")
                CASE 20 RETURN HASH("FAGGIO")
                CASE 21 RETURN HASH("FAGGIO2")
                CASE 22 RETURN HASH("FAGGIO3")
                CASE 23 RETURN HASH("FCR")
                CASE 24 RETURN HASH("FCR2")
                CASE 25 RETURN HASH("GARGOYLE")
                CASE 26 RETURN HASH("HAKUCHOU")
                CASE 27 RETURN HASH("HAKUCHOU2")
                CASE 28 RETURN HASH("HEXER")
                CASE 29 RETURN HASH("INNOVATION")
                CASE 30 RETURN HASH("LECTRO")
                CASE 31 RETURN HASH("MANCHEZ")
                CASE 32 RETURN HASH("MANCHEZ2")
                CASE 33 RETURN HASH("MANCHEZ3")
                CASE 34 RETURN HASH("NEMESIS")
                CASE 35 RETURN HASH("NIGHTBLADE")
                CASE 36 RETURN HASH("OPPRESSOR")
                CASE 37 RETURN HASH("OPPRESSOR2")
                CASE 38 RETURN HASH("PCJ")
                CASE 39 RETURN HASH("PIZZABOY")
                CASE 40 RETURN HASH("POWERSURGE")
                CASE 41 RETURN HASH("RATBIKE")
                CASE 42 RETURN HASH("REEVER")
                CASE 43 RETURN HASH("RROCKET")
                CASE 44 RETURN HASH("RUFFIAN")
                CASE 45 RETURN HASH("SANCHEZ")
                CASE 46 RETURN HASH("SANCHEZ2")
                CASE 47 RETURN HASH("SANCTUS")
                CASE 48 RETURN HASH("SHINOBI")
                CASE 49 RETURN HASH("SHOTARO")
                CASE 50 RETURN HASH("SOVEREIGN")
                CASE 51 RETURN HASH("STRYDER")
                CASE 52 RETURN HASH("THRUST")
                CASE 53 RETURN HASH("VADER")
                CASE 54 RETURN HASH("VINDICATOR")
                CASE 55 RETURN HASH("VORTEX")
                CASE 56 RETURN HASH("WOLFSBANE")
                CASE 57 RETURN HASH("ZOMBIEA")
                CASE 58 RETURN HASH("ZOMBIEB")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_OFF_ROAD
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("BFINJECTION")
                CASE 1  RETURN HASH("BIFTA")
                CASE 2  RETURN HASH("BLAZER")
                CASE 3  RETURN HASH("BLAZER2")
                CASE 4  RETURN HASH("BLAZER3")
                CASE 5  RETURN HASH("BLAZER4")
                CASE 6  RETURN HASH("BLAZER5")
                CASE 7  RETURN HASH("BODHI2")
                CASE 8  RETURN HASH("BOOR")
                CASE 9  RETURN HASH("BRAWLER")
                CASE 10 RETURN HASH("BRUISER")
                CASE 11 RETURN HASH("BRUISER2")
                CASE 12 RETURN HASH("BRUISER3")
                CASE 13 RETURN HASH("BRUTUS")
                CASE 14 RETURN HASH("BRUTUS2")
                CASE 15 RETURN HASH("BRUTUS3")
                CASE 16 RETURN HASH("CARACARA")
                CASE 17 RETURN HASH("CARACARA2")
                CASE 18 RETURN HASH("DLOADER")
                CASE 19 RETURN HASH("DRAUGUR")
                CASE 20 RETURN HASH("DUBSTA3")
                CASE 21 RETURN HASH("DUNE")
                CASE 22 RETURN HASH("DUNE2")
                CASE 23 RETURN HASH("DUNE3")
                CASE 24 RETURN HASH("DUNE4")
                CASE 25 RETURN HASH("DUNE5")
                CASE 26 RETURN HASH("EVERON")
                CASE 27 RETURN HASH("FIREBOLT")
                CASE 28 RETURN HASH("FREECRAWLER")
                CASE 29 RETURN HASH("HELLION")
                CASE 30 RETURN HASH("INSURGENT")
                CASE 31 RETURN HASH("INSURGENT2")
                CASE 32 RETURN HASH("INSURGENT3")
                CASE 33 RETURN HASH("KALAHARI")
                CASE 34 RETURN HASH("KAMACHO")
                CASE 35 RETURN HASH("L35")
                CASE 36 RETURN HASH("MARSHALL")
                CASE 37 RETURN HASH("MENACER")
                CASE 38 RETURN HASH("MESA3")
                CASE 39 RETURN HASH("MONSTER")
                CASE 40 RETURN HASH("MONSTER3")
                CASE 41 RETURN HASH("MONSTER4")
                CASE 42 RETURN HASH("MONSTER5")
                CASE 43 RETURN HASH("MONSTROCITI")
                CASE 44 RETURN HASH("NIGHTSHARK")
                CASE 45 RETURN HASH("OUTLAW")
                CASE 46 RETURN HASH("PATRIOT3")
                CASE 47 RETURN HASH("RANCHERXL")
                CASE 48 RETURN HASH("RANCHERXL2")
                CASE 49 RETURN HASH("RATEL")
                CASE 50 RETURN HASH("RCBANDITO")
                CASE 51 RETURN HASH("REBEL")
                CASE 52 RETURN HASH("REBEL2")
                CASE 53 RETURN HASH("RIATA")
                CASE 54 RETURN HASH("SANDKING")
                CASE 55 RETURN HASH("SANDKING2")
                CASE 56 RETURN HASH("TECHNICAL")
                CASE 57 RETURN HASH("TECHNICAL2")
                CASE 58 RETURN HASH("TECHNICAL3")
                CASE 59 RETURN HASH("TERMINUS")
                CASE 60 RETURN HASH("TROPHYTRUCK")
                CASE 61 RETURN HASH("TROPHYTRUCK2")
                CASE 62 RETURN HASH("VAGRANT")
                CASE 63 RETURN HASH("VERUS")
                CASE 64 RETURN HASH("WINKY")
                CASE 65 RETURN HASH("YOSEMITE3")
                CASE 66 RETURN HASH("YOSEMITE1500")
                CASE 67 RETURN HASH("ZHABA")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_INDUSTRIAL
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("BULLDOZER")
                CASE 1  RETURN HASH("CUTTER")
                CASE 2  RETURN HASH("DUMP")
                CASE 3  RETURN HASH("FLATBED")
                CASE 4  RETURN HASH("GUARDIAN")
                CASE 5  RETURN HASH("HANDLER")
                CASE 6  RETURN HASH("MIXER")
                CASE 7  RETURN HASH("MIXER2")
                CASE 8  RETURN HASH("RUBBLE")
                CASE 9  RETURN HASH("TIPTRUCK")
                CASE 10 RETURN HASH("TIPTRUCK2")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_UTILITY
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("AIRTUG")
                CASE 1  RETURN HASH("ARMYTANKER")
                CASE 2  RETURN HASH("ARMYTRAILER")
                CASE 3  RETURN HASH("ARMYTRAILER2")
                CASE 4  RETURN HASH("BALETRAILER")
                CASE 5  RETURN HASH("BOATTRAILER")
                CASE 6  RETURN HASH("BOATTRAILER2")
                CASE 7  RETURN HASH("BOATTRAILER3")
                CASE 8  RETURN HASH("CADDY")
                CASE 9  RETURN HASH("CADDY2")
                CASE 10 RETURN HASH("CADDY3")
                CASE 11 RETURN HASH("DOCKTRAILER")
                CASE 12 RETURN HASH("DOCKTUG")
                CASE 13 RETURN HASH("FORKLIFT")
                CASE 14 RETURN HASH("FREIGHTTRAILER")
                CASE 15 RETURN HASH("GRAINTRAILER")
                CASE 16 RETURN HASH("MOWER")
                CASE 17 RETURN HASH("PROPTRAILER")
                CASE 18 RETURN HASH("RAKETRAILER")
                CASE 19 RETURN HASH("RIPLEY")
                CASE 20 RETURN HASH("SADLER")
                CASE 21 RETURN HASH("SADLER2")
                CASE 22 RETURN HASH("SCRAP")
                CASE 23 RETURN HASH("SLAMTRUCK")
                CASE 24 RETURN HASH("TANKER")
                CASE 25 RETURN HASH("TANKER2")
                CASE 26 RETURN HASH("TOWTRUCK")
                CASE 27 RETURN HASH("TOWTRUCK2")
                CASE 28 RETURN HASH("TOWTRUCK3")
                CASE 29 RETURN HASH("TOWTRUCK4")
                CASE 30 RETURN HASH("TR2")
                CASE 31 RETURN HASH("TR3")
                CASE 32 RETURN HASH("TR4")
                CASE 33 RETURN HASH("TRACTOR")
                CASE 34 RETURN HASH("TRACTOR2")
                CASE 35 RETURN HASH("TRACTOR3")
                CASE 36 RETURN HASH("TRAILERLARGE")
                CASE 37 RETURN HASH("TRAILERLOGS")
                CASE 38 RETURN HASH("TRAILERS")
                CASE 39 RETURN HASH("TRAILERS2")
                CASE 40 RETURN HASH("TRAILERS3")
                CASE 41 RETURN HASH("TRAILERS4")
                CASE 42 RETURN HASH("TRAILERS5")
                CASE 43 RETURN HASH("TRAILERSMALL")
                CASE 44 RETURN HASH("TRFLAT")
                CASE 45 RETURN HASH("TVTRAILER")
                CASE 46 RETURN HASH("TVTRAILER2")
                CASE 47 RETURN HASH("UTILLITRUCK")
                CASE 48 RETURN HASH("UTILLITRUCK2")
                CASE 49 RETURN HASH("UTILLITRUCK3")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_VAN
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("BISON")
                CASE 1  RETURN HASH("BISON2")
                CASE 2  RETURN HASH("BISON3")
                CASE 3  RETURN HASH("BOBCATXL")
                CASE 4  RETURN HASH("BOXVILLE")
                CASE 5  RETURN HASH("BOXVILLE2")
                CASE 6  RETURN HASH("BOXVILLE3")
                CASE 7  RETURN HASH("BOXVILLE4")
                CASE 8  RETURN HASH("BOXVILLE5")
                CASE 9  RETURN HASH("BOXVILLE6")
                CASE 10 RETURN HASH("BURRITO")
                CASE 11 RETURN HASH("BURRITO2")
                CASE 12 RETURN HASH("BURRITO3")
                CASE 13 RETURN HASH("BURRITO4")
                CASE 14 RETURN HASH("BURRITO5")
                CASE 15 RETURN HASH("CAMPER")
                CASE 16 RETURN HASH("GBURRITO")
                CASE 17 RETURN HASH("GBURRITO2")
                CASE 18 RETURN HASH("JOURNEY")
                CASE 19 RETURN HASH("JOURNEY2")
                CASE 20 RETURN HASH("MINIVAN")
                CASE 21 RETURN HASH("MINIVAN2")
                CASE 22 RETURN HASH("PARADISE")
                CASE 23 RETURN HASH("PONY")
                CASE 24 RETURN HASH("PONY2")
                CASE 25 RETURN HASH("RUMPO")
                CASE 26 RETURN HASH("RUMPO2")
                CASE 27 RETURN HASH("RUMPO3")
                CASE 28 RETURN HASH("SPEEDO")
                CASE 29 RETURN HASH("SPEEDO2")
                CASE 30 RETURN HASH("SPEEDO4")
                CASE 31 RETURN HASH("SPEEDO5")
                CASE 32 RETURN HASH("SURFER")
                CASE 33 RETURN HASH("SURFER2")
                CASE 34 RETURN HASH("SURFER3")
                CASE 35 RETURN HASH("TACO")
                CASE 36 RETURN HASH("YOUGA")
                CASE 37 RETURN HASH("YOUGA2")
                CASE 38 RETURN HASH("YOUGA3")
                CASE 39 RETURN HASH("YOUGA4")
                CASE 40 RETURN HASH("YOUGA5")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_CYCLE
            SWITCH iVehicleIndex
                CASE 0 RETURN HASH("BMX")
                CASE 1 RETURN HASH("CRUISER")
                CASE 2 RETURN HASH("FIXTER")
                CASE 3 RETURN HASH("INDUCTOR")
                CASE 4 RETURN HASH("INDUCTOR2")
                CASE 5 RETURN HASH("SCORCHER")
                CASE 6 RETURN HASH("TRIBIKE")
                CASE 7 RETURN HASH("TRIBIKE2")
                CASE 8 RETURN HASH("TRIBIKE3")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_BOAT
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("AVISA")
                CASE 1  RETURN HASH("DINGHY")
                CASE 2  RETURN HASH("DINGHY2")
                CASE 3  RETURN HASH("DINGHY3")
                CASE 4  RETURN HASH("DINGHY4")
                CASE 5  RETURN HASH("DINGHY5")
                CASE 6  RETURN HASH("JETMAX")
                CASE 7  RETURN HASH("KOSATKA")
                CASE 8  RETURN HASH("LONGFIN")
                CASE 9  RETURN HASH("MARQUIS")
                CASE 10 RETURN HASH("PATROLBOAT")
                CASE 11 RETURN HASH("PREDATOR")
                CASE 12 RETURN HASH("SEASHARK")
                CASE 13 RETURN HASH("SEASHARK2")
                CASE 14 RETURN HASH("SEASHARK3")
                CASE 15 RETURN HASH("SPEEDER")
                CASE 16 RETURN HASH("SPEEDER2")
                CASE 17 RETURN HASH("SQUALO")
                CASE 18 RETURN HASH("SUBMERSIBLE")
                CASE 19 RETURN HASH("SUBMERSIBLE2")
                CASE 20 RETURN HASH("SUNTRAP")
                CASE 21 RETURN HASH("TORO")
                CASE 22 RETURN HASH("TORO2")
                CASE 23 RETURN HASH("TROPIC")
                CASE 24 RETURN HASH("TROPIC2")
                CASE 25 RETURN HASH("TUG")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_HELICOPTER
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("AKULA")
                CASE 1  RETURN HASH("ANNIHILATOR")
                CASE 2  RETURN HASH("ANNIHILATOR2")
                CASE 3  RETURN HASH("BUZZARD")
                CASE 4  RETURN HASH("BUZZARD2")
                CASE 5  RETURN HASH("CARGOBOB")
                CASE 6  RETURN HASH("CARGOBOB2")
                CASE 7  RETURN HASH("CARGOBOB3")
                CASE 8  RETURN HASH("CARGOBOB4")
                CASE 9  RETURN HASH("CARGOBOB5")
                CASE 10 RETURN HASH("CONADA")
                CASE 11 RETURN HASH("CONADA2")
                CASE 12 RETURN HASH("FROGGER")
                CASE 13 RETURN HASH("FROGGER2")
                CASE 14 RETURN HASH("HAVOK")
                CASE 15 RETURN HASH("HUNTER")
                CASE 16 RETURN HASH("MAVERICK")
                CASE 17 RETURN HASH("POLMAV")
                CASE 18 RETURN HASH("SAVAGE")
                CASE 19 RETURN HASH("SEASPARROW")
                CASE 20 RETURN HASH("SEASPARROW2")
                CASE 21 RETURN HASH("SEASPARROW3")
                CASE 22 RETURN HASH("SKYLIFT")
                CASE 23 RETURN HASH("SUPERVOLITO")
                CASE 24 RETURN HASH("SUPERVOLITO2")
                CASE 25 RETURN HASH("SWIFT")
                CASE 26 RETURN HASH("SWIFT2")
                CASE 27 RETURN HASH("VALKYRIE")
                CASE 28 RETURN HASH("VALKYRIE2")
                CASE 29 RETURN HASH("VOLATUS")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_PLANE
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("ALKONOST")
                CASE 1  RETURN HASH("ALPHAZ1")
                CASE 2  RETURN HASH("AVENGER")
                CASE 3  RETURN HASH("AVENGER2")
                CASE 4  RETURN HASH("AVENGER3")
                CASE 5  RETURN HASH("AVENGER4")
                CASE 6  RETURN HASH("BESRA")
                CASE 7  RETURN HASH("BLIMP")
                CASE 8  RETURN HASH("BLIMP2")
                CASE 9  RETURN HASH("BLIMP3")
                CASE 10 RETURN HASH("BOMBUSHKA")
                CASE 11 RETURN HASH("CARGOPLANE")
                CASE 12 RETURN HASH("CARGOPLANE2")
                CASE 13 RETURN HASH("CUBAN800")
                CASE 14 RETURN HASH("DODO")
                CASE 15 RETURN HASH("DUSTER")
                CASE 16 RETURN HASH("DUSTER2")
                CASE 17 RETURN HASH("HOWARD")
                CASE 18 RETURN HASH("HYDRA")
                CASE 19 RETURN HASH("JET")
                CASE 20 RETURN HASH("LAZER")
                CASE 21 RETURN HASH("LUXOR")
                CASE 22 RETURN HASH("LUXOR2")
                CASE 23 RETURN HASH("MAMMATUS")
                CASE 24 RETURN HASH("MICROLIGHT")
                CASE 25 RETURN HASH("MILJET")
                CASE 26 RETURN HASH("MOGUL")
                CASE 27 RETURN HASH("MOLOTOK")
                CASE 28 RETURN HASH("NIMBUS")
                CASE 29 RETURN HASH("NOKOTA")
                CASE 30 RETURN HASH("PYRO")
                CASE 31 RETURN HASH("RAIJU")
                CASE 32 RETURN HASH("ROGUE")
                CASE 33 RETURN HASH("SEABREEZE")
                CASE 34 RETURN HASH("SHAMAL")
                CASE 35 RETURN HASH("STARLING")
                CASE 36 RETURN HASH("STREAMER216")
                CASE 37 RETURN HASH("STRIKEFORCE")
                CASE 38 RETURN HASH("STUNT")
                CASE 39 RETURN HASH("TITAN")
                CASE 40 RETURN HASH("TITAN2")
                CASE 41 RETURN HASH("TULA")
                CASE 42 RETURN HASH("VELUM")
                CASE 43 RETURN HASH("VELUM2")
                CASE 44 RETURN HASH("VESTRA")
                CASE 45 RETURN HASH("VOLATOL")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_SERVICE
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("AIRBUS")
                CASE 1  RETURN HASH("BRICKADE")
                CASE 2  RETURN HASH("BRICKADE2")
                CASE 3  RETURN HASH("BUS")
                CASE 4  RETURN HASH("COACH")
                CASE 5  RETURN HASH("PBUS2")
                CASE 6  RETURN HASH("RALLYTRUCK")
                CASE 7  RETURN HASH("RENTALBUS")
                CASE 8  RETURN HASH("TAXI")
                CASE 9  RETURN HASH("TOURBUS")
                CASE 10 RETURN HASH("TRASH")
                CASE 11 RETURN HASH("TRASH2")
                CASE 12 RETURN HASH("WASTELANDER")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_EMERGENCY
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("AMBULANCE")
                CASE 1  RETURN HASH("FBI")
                CASE 2  RETURN HASH("FBI2")
                CASE 3  RETURN HASH("FIRETRUK")
                CASE 4  RETURN HASH("LGUARD")
                CASE 5  RETURN HASH("PBUS")
                CASE 6  RETURN HASH("POLCARACARA")
                CASE 7  RETURN HASH("POLCOQUETTE4")
                CASE 8  RETURN HASH("POLDOMINATOR10")
                CASE 9  RETURN HASH("POLDORADO")
                CASE 10 RETURN HASH("POLFACTION2")
                CASE 11 RETURN HASH("POLGAUNTLET")
                CASE 12 RETURN HASH("POLGREENWOOD")
                CASE 13 RETURN HASH("POLICE")
                CASE 14 RETURN HASH("POLICE2")
                CASE 15 RETURN HASH("POLICE3")
                CASE 16 RETURN HASH("POLICE4")
                CASE 17 RETURN HASH("POLICE5")
                CASE 18 RETURN HASH("POLICEB")
                CASE 19 RETURN HASH("POLICEOLD1")
                CASE 20 RETURN HASH("POLICEOLD2")
                CASE 21 RETURN HASH("POLICET")
                CASE 22 RETURN HASH("POLICET3")
                CASE 23 RETURN HASH("POLIMPALER5")
                CASE 24 RETURN HASH("POLIMPALER6")
                CASE 25 RETURN HASH("POLTERMINUS")
                CASE 26 RETURN HASH("PRANGER")
                CASE 27 RETURN HASH("RIOT")
                CASE 28 RETURN HASH("RIOT2")
                CASE 29 RETURN HASH("SHERIFF")
                CASE 30 RETURN HASH("SHERIFF2")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_MILITARY
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("APC")
                CASE 1  RETURN HASH("BARRACKS")
                CASE 2  RETURN HASH("BARRACKS2")
                CASE 3  RETURN HASH("BARRACKS3")
                CASE 4  RETURN HASH("BARRAGE")
                CASE 5  RETURN HASH("CHERNOBOG")
                CASE 6  RETURN HASH("CRUSADER")
                CASE 7  RETURN HASH("HALFTRACK")
                CASE 8  RETURN HASH("KHANJALI")
                CASE 9  RETURN HASH("MINITANK")
                CASE 10 RETURN HASH("RHINO")
                CASE 11 RETURN HASH("SCARAB")
                CASE 12 RETURN HASH("SCARAB2")
                CASE 13 RETURN HASH("SCARAB3")
                CASE 14 RETURN HASH("THRUSTER")
                CASE 15 RETURN HASH("TRAILERSMALL2")
                CASE 16 RETURN HASH("VETIR")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_COMMERCIAL
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("BENSON")
                CASE 1  RETURN HASH("BENSON2")
                CASE 2  RETURN HASH("BIFF")
                CASE 3  RETURN HASH("CERBERUS")
                CASE 4  RETURN HASH("CERBERUS2")
                CASE 5  RETURN HASH("CERBERUS3")
                CASE 6  RETURN HASH("HAULER")
                CASE 7  RETURN HASH("HAULER2")
                CASE 8  RETURN HASH("MULE")
                CASE 9  RETURN HASH("MULE2")
                CASE 10 RETURN HASH("MULE3")
                CASE 11 RETURN HASH("MULE4")
                CASE 12 RETURN HASH("MULE5")
                CASE 13 RETURN HASH("PACKER")
                CASE 14 RETURN HASH("PHANTOM")
                CASE 15 RETURN HASH("PHANTOM2")
                CASE 16 RETURN HASH("PHANTOM3")
                CASE 17 RETURN HASH("PHANTOM4")
                CASE 18 RETURN HASH("POUNDER")
                CASE 19 RETURN HASH("POUNDER2")
                CASE 20 RETURN HASH("STOCKADE")
                CASE 21 RETURN HASH("STOCKADE3")
                CASE 22 RETURN HASH("TERBYTE")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_RAIL
            SWITCH iVehicleIndex
                CASE 0  RETURN HASH("CABLECAR")
                CASE 1  RETURN HASH("FREIGHT")
                CASE 2  RETURN HASH("FREIGHT2")
                CASE 3  RETURN HASH("FREIGHTCAR")
                CASE 4  RETURN HASH("FREIGHTCAR2")
                CASE 5  RETURN HASH("FREIGHTCAR3")
                CASE 6  RETURN HASH("FREIGHTCONT1")
                CASE 7  RETURN HASH("FREIGHTCONT2")
                CASE 8  RETURN HASH("FREIGHTGRAIN")
                CASE 9  RETURN HASH("METROTRAIN")
                CASE 10 RETURN HASH("TANKERCAR")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
        CASE VC_OPEN_WHEEL
            SWITCH iVehicleIndex
                CASE 0 RETURN HASH("FORMULA")
                CASE 1 RETURN HASH("FORMULA2")
                CASE 2 RETURN HASH("OPENWHEEL1")
                CASE 3 RETURN HASH("OPENWHEEL2")
                DEFAULT RETURN 0
            ENDSWITCH
        BREAK
    ENDSWITCH
    
    RETURN 0
ENDFUNC
