USING "util_world.sch"

PROC FEATURES_WORLD_HEADSHOT_NEARBY_ENEMIES()
    PED_INDEX piPeds[32]
    INT iPedCount = GET_PED_NEARBY_PEDS(PLAYER_PED_ID(), piPeds, PED_TYPE_NETWORK_PLAYER)

    INT i
    FOR i = 0 to iPedCount
        IF IS_PED_IN_COMBAT(piPeds[i], PLAYER_PED_ID())
            VECTOR vShootFrom = GET_ENTITY_COORDS(piPeds[i], TRUE)
            vShootFrom.z = vShootFrom.z + 1.0
            VECTOR vShootTo = GET_PED_BONE_COORDS(piPeds[i], SKEL_Head, <<0, 0, 0>>) // head
            SHOOT_SINGLE_BULLET_BETWEEN_COORDS(vShootFrom, vShootTo, 5000, FALSE, HASH("WEAPON_HEAVYSNIPER"), PLAYER_PED_ID(), FALSE, FALSE, 2000)
        ENDIF
    ENDFOR
ENDPROC

PROC FEATURES_WORLD_BLACKOUT(BOOL bEnabled)
    SET_ARTIFICIAL_LIGHTS_STATE(bEnabled)
ENDPROC

PROC FEATURES_WORLD_NIGHT_VISION(BOOL bEnabled)
    SET_NIGHTVISION(bEnabled)
ENDPROC

PROC FEATURES_WORLD_THERMAL_VISION(BOOL bEnabled)
    SET_SEETHROUGH(bEnabled)
ENDPROC

PROC FEATURES_WORLD_RIOT_MODE(BOOL bEnabled)
    SET_RIOT_MODE_ENABLED(bEnabled)
ENDPROC

PROC FEATURES_WORLD_SET_TIME(INT iHour, INT iMinute, INT iSecond)
    SET_CLOCK_TIME(iHour, iMinute, iSecond)
ENDPROC

PROC FEATURES_WORLD_PAUSE_TIME(BOOL bEnabled)
    PAUSE_CLOCK(bEnabled)
ENDPROC

PROC FEATURES_WORLD_SET_WEATHER(STRING codeName)
    SET_OVERRIDE_WEATHER(codeName)
	
    BOOL bEnableSnow = GET_HASH_KEY(codeName) = HASH("XMAS") OR GET_HASH_KEY(codeName) = HASH("SNOW_HALLOWEEN")
    UTIL_WORLD_ENABLE_SNOW(bEnableSnow)
ENDPROC

PROC WORLD_LOAD_IPL_SET(BOOL bLoad)
    STRING sName = CALL sIPLSetData.fpGetIPLNameByIndex(0)
    INT iIndex = 0
    WHILE NOT IS_STRING_NULL_OR_EMPTY(sName)
        sName = CALL sIPLSetData.fpGetIPLNameByIndex(iIndex)
        IF bLoad
            IF UTIL_WORLD_SHOULD_REMOVE_THIS_IPL_ON_LOAD(GET_HASH_KEY(sName))
                UTIL_WORLD_LOAD_IPL(sName, FALSE)
            ELSE
                UTIL_WORLD_LOAD_IPL(sName, TRUE)
            ENDIF
        ELSE
            IF UTIL_WORLD_SHOULD_REMOVE_THIS_IPL_ON_LOAD(GET_HASH_KEY(sName))
                UTIL_WORLD_LOAD_IPL(sName, TRUE)
            ELSE
                UTIL_WORLD_LOAD_IPL(sName, FALSE)
            ENDIF
        ENDIF
        iIndex++
    ENDWHILE
ENDPROC

PROC WORLD_LOAD_IPL(STRING sName, BOOL bLoad)
    UTIL_WORLD_LOAD_IPL(sName, bLoad)
ENDPROC
