USING "util_weapons.sch"

PROC FEATURES_WEAPONS_FILL_AMMO()
    INT iIndex = 0
    REPEAT NUM_WEAPONS iIndex
        INT iAmmo = 0
        INT iWeaponHash = GET_WEAPON_HASH_BY_INDEX(iIndex)
        GET_MAX_AMMO(PLAYER_PED_ID(), iWeaponHash, iAmmo)
        SET_PED_AMMO(PLAYER_PED_ID(), iWeaponHash, iAmmo, FALSE)
    ENDREPEAT
ENDPROC

PROC FEATURES_WEAPONS_GET_ALL_WEAPONS()
    INT iIndex = 0
    REPEAT NUM_WEAPONS iIndex
        INT iWeaponHash = GET_WEAPON_HASH_BY_INDEX(iIndex)
        GIVE_WEAPON_TO_PED(PLAYER_PED_ID(), iWeaponHash, 9999, FALSE, TRUE)
    ENDREPEAT
ENDPROC

PROC FEATURES_WEAPONS_REMOVE_ALL_WEAPONS()
    REMOVE_ALL_PED_WEAPONS(PLAYER_PED_ID(), TRUE)
ENDPROC

PROC FEATURES_WEAPONS_REMOVE_CURRENT_WEAPON()
    INT iCurrWeapon
    GET_CURRENT_PED_WEAPON(PLAYER_PED_ID(), iCurrWeapon, TRUE)
    REMOVE_WEAPON_FROM_PED(PLAYER_PED_ID(), iCurrWeapon)
ENDPROC

PROC FEATURES_WEAPONS_INFINITE_AMMO(BOOL bEnabled)
    SET_PED_INFINITE_AMMO(PLAYER_PED_ID(), bEnabled, 0)
ENDPROC

PROC FEATURES_WEAPONS_INFINITE_CLIP(BOOL bEnabled)
    SET_PED_INFINITE_AMMO_CLIP(PLAYER_PED_ID(), bEnabled)
ENDPROC

PROC FEATURES_WEAPONS_EXPLOSIVE_AMMO()
    SET_EXPLOSIVE_AMMO_THIS_FRAME(PLAYER_ID())
ENDPROC

PROC FEATURES_WEAPONS_EXPLOSIVE_MELEE()
    SET_EXPLOSIVE_MELEE_THIS_FRAME(PLAYER_ID())
ENDPROC

PROC FEATURES_WEAPONS_FIRE_AMMO()
    SET_FIRE_AMMO_THIS_FRAME(PLAYER_ID())
ENDPROC

PROC FEATURES_WEAPONS_GIVE_WEAPON(INT iWeaponHash)
    GIVE_WEAPON_TO_PED(PLAYER_PED_ID(), iWeaponHash, 9999, FALSE, TRUE)
ENDPROC
