CONST_INT   INT_MIN     -2147483647
CONST_INT   INT_MAX      2147483647
CONST_FLOAT FLOAT_MIN   -2147483647.0
CONST_FLOAT FLOAT_MAX    2147483647.0
CONST_FLOAT TOOLTIP_POS  0.880

FUNC FLOAT GET_STRING_WIDTH(STRING sString)
    BEGIN_TEXT_COMMAND_GET_SCREEN_WIDTH_OF_DISPLAY_TEXT("STRING")
    ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME(sString)
    RETURN END_TEXT_COMMAND_GET_SCREEN_WIDTH_OF_DISPLAY_TEXT(TRUE)
ENDFUNC

FUNC FLOAT GET_INTEGER_WIDTH(INT iNumber)
    BEGIN_TEXT_COMMAND_GET_SCREEN_WIDTH_OF_DISPLAY_TEXT("NUMBER")
    ADD_TEXT_COMPONENT_INTEGER(iNumber)
    RETURN END_TEXT_COMMAND_GET_SCREEN_WIDTH_OF_DISPLAY_TEXT(TRUE)
ENDFUNC

FUNC FLOAT GET_FLOAT_WIDTH(FLOAT fNumber)
    BEGIN_TEXT_COMMAND_GET_SCREEN_WIDTH_OF_DISPLAY_TEXT("NUMBER")
    ADD_TEXT_COMPONENT_FLOAT(fNumber, 2)
    RETURN END_TEXT_COMMAND_GET_SCREEN_WIDTH_OF_DISPLAY_TEXT(TRUE)
ENDFUNC

FUNC INT GET_NUM_LINES_TOOLTIP(STRING sString)
    BEGIN_TEXT_COMMAND_GET_NUMBER_OF_LINES_FOR_STRING("STRING")
    ADD_TEXT_COMPONENT_SUBSTRING_PLAYER_NAME(sString)
    RETURN END_TEXT_COMMAND_GET_NUMBER_OF_LINES_FOR_STRING((TOOLTIP_POS / (TOOLTIP_POS * 2.0)) - 0.1, 0.544 * 0.5)
ENDFUNC

FUNC INT CLAMP_INTEGER(INT iValue, INT iMin, INT iMax)
    IF iValue > iMax
        RETURN iMax
    ELIF iValue < iMin
        RETURN iMin
    ENDIF
    RETURN iValue
ENDFUNC

FUNC FLOAT CLAMP_FLOAT(FLOAT fValue, FLOAT fMin, FLOAT fMax)
    IF fValue > fMax
        RETURN fMax
    ELIF fValue < fMin
        RETURN fMin
    ENDIF
    RETURN fValue
ENDFUNC

FUNC BOOL STRING_TO_FLOAT(STRING sString, FLOAT &fResult)
    IF NOT IS_STRING_NULL_OR_EMPTY(sString)
        INT i        = GET_LENGTH_OF_LITERAL_STRING(sString) - 1
        FLOAT fBase  = 0.01

        WHILE i <> -1
            STRING sChar      = GET_CHARACTER_FROM_AUDIO_CONVERSATION_FILENAME(sString, i, i + 1)
            INT iCharAsInt    = -1
            BOOL bIsCharNumber = STRING_TO_INT(sChar, iCharAsInt)

            IF NOT bIsCharNumber
                BOOL bCharIsMinus = ARE_STRINGS_EQUAL(sChar, "-")
                BOOL bCharIsPoint = ARE_STRINGS_EQUAL(sChar, ".")

                IF bCharIsMinus
                    fResult *= -1.0
                ELIF NOT bCharIsPoint
                    RETURN FALSE
                ENDIF
            ELSE
                fResult += TO_FLOAT(iCharAsInt) * fBase
                fBase *= 10.0
            ENDIF

            i--
        ENDWHILE
    ELSE
        RETURN FALSE
    ENDIF

    RETURN TRUE
ENDFUNC

FUNC STRING PICK_STRING(BOOL bVal, STRING sTrue, STRING sFalse)
    IF bVal
        RETURN sTrue
    ENDIF
	
    RETURN sFalse
ENDFUNC

FUNC BOOL IS_VECTOR_ZERO(VECTOR vVector)
    IF vVector.x = 0.0 AND vVector.y = 0.0 AND vVector.z = 0.0
        RETURN TRUE
    ENDIF
    
    RETURN FALSE
ENDFUNC
